//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksGenres
    {
        public int ID { get; set; }
        public int BookId { get; set; }
        public int GenreId { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
