//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnfreezeApplications
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int TargetTypeId { get; set; }
        public Nullable<int> TargetBookId { get; set; }
        public string Reason { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string Status { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual TargetTypes TargetTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
